# Generated by Django 5.2.13 on 2026-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('pending_payment', 'Pending Payment Verification'), ('paid', 'Paid / Confirmed'), ('completed', 'Completed'), ('rejected', 'Payment Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
