# Generated by Django 4.2.7 on 2026-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_status_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
