# Generated by Django 4.2.7 on 2026-04-16 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('car_detailing', 'Car Detailing'), ('office_cleaning', 'Office Deep Cleaning'), ('house_cleaning', 'House Cleaning'), ('compound_cleaning', 'Compound Cleaning'), ('graphic_design', 'Graphic Design'), ('website_development', 'Website Development'), ('system_development', 'System Development'), ('chauffeur_services', 'Chauffeur Services')], max_length=50, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_hours', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
